# Generated by Django 4.1.13 on 2024-04-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ordermodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orderdatetime",
                    models.DateTimeField(auto_created=True, auto_now=True),
                ),
                ("userid", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("useremail", models.EmailField(max_length=254)),
                ("productid", models.CharField(max_length=200)),
                ("qty", models.CharField(default="", max_length=200)),
                ("orderamount", models.CharField(max_length=200)),
                ("paymentvia", models.CharField(max_length=200)),
                ("paymentmethod", models.CharField(max_length=200)),
                ("transactionid", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="wishlistModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderId", models.CharField(max_length=20)),
                ("itemId", models.CharField(max_length=20)),
                ("userId", models.CharField(max_length=20)),
                ("qty", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=20)),
                ("totalPrice", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="sendmessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Item_id", models.CharField(default="", max_length=255)),
                ("message", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "reciver_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reciver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chat Messages",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(default="Uncategorized", max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("condition", models.CharField(max_length=255)),
                ("photos", models.ImageField(upload_to="items/photos")),
                (
                    "seller_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
